export const INIT_OBJECT = 'INIT_OBJECT';
export const INIT_ADD = 'INIT_ADD';
export const ADD_OBJECT = 'ADD_OBJECT';
export const ADDED_OBJECT = 'ADDED_OBJECT';
export const GET_OBJECTS = 'GET_OBJECTS';
export const SIGN_UP = 'SIGN_UP';
export const LOG_IN = 'LOG_IN';
export const SACUVAJ_PACIJENTE = 'SACUVAJ_PACIJENTE';
export const SACUVAJ_KLINIKE = 'SACUVAJ_KLINIKE';
export const SACUVAJ_KARTON = 'SACUVAJ_KARTON';
export const SACUVAJ_PREGLED = 'SACUVAJ_PREGLED';
export const SACUVAJ_SALE = 'SACUVAJ_SALE';
export const SACUVAJ_DOKTORE = 'SACUVAJ_DOKTORE';
export const SACUVAJ_TIPOVE_PREGLEDA = 'SACUVAJ_TIPOVE_PREGLEDA';
export const SACUVAJ_PREGLEDE = 'SACUVAJ_PREGLEDE';
export const SACUVAJ_PRIJAVLJENOG_KORISNIKA = 'SACUVAJ_PRIJAVLJENOG_KORISNIKA';
export const VRATI_SORTIRANE_PACIJENTE = 'VRATI_SORTIRANE_PACIJENTE';
export const SACUVAJ_ODGOVOR = 'SACUVAJ_ODGOVOR';
export const SACUVAJ_OBELEZENU_KLINIKU = 'SACUVAJ_OBELEZENU_KLINIKU';
export const SACUVAJ_POSLATI_ZAHTEV = 'SACUVAJ_POSLATI_ZAHTEV';
export const SACUVAJ_SVE_ZAHTEVE = 'SACUVAJ_SVE_ZAHTEVE';
export const SACUVAJ_ODGOVOR_POTVRDE = 'SACUVAJ_ODGOVOR_POTVRDE';
export const SACUVAJ_DOKTORE_ID = 'SACUVAJ_DOKTORE_ID';
export const SACUVAJ_OBELEZENOG_PACIJENTA = 'SACUVAJ_OBELEZENOG_PACIJENTA';
export const SACUVAJ_BOLESTI = 'SACUVAJ_BOLESTI';
export const SACUVAJ_LEKOVE = 'SACUVAJ_LEKOVE';
export const SACUVAJ_PREGLED_KARTON = 'SACUVAJ_PREGLED_KARTON';
export const SACUVAJ_PRETRAGU = 'SACUVAJ_PRETRAGU';
export const SACUVAJ_POTREBNE_DOKTORE = 'SACUVAJ_POTREBNE_DOKTORE';
export const SACUVAJ_MOGUCNOST_REZERVACIJE = 'SACUVAJ_MOGUCNOST_REZERVACIJE';
export const SACUVAJ_KLINIKU_PROFILA = 'SACUVAJ_KLINIKU_PROFILA';
export const SACUVAJ_ODGOVOR_DOKTORA = 'SACUVAJ_ODGOVOR_DOKTORA';
export const SACUVAJ_REZERVACIJE = 'SACUVAJ_REZERVACIJE';
export const OBRISI_PRIJAVLJENOG = 'OBRISI_PRIJAVLJENOG';








//export const SACUVAJ_PREGLEDE = 'SACUVAJ_PREGLEDE';