export const INIT_OBJECT = 'INIT_OBJECT';
export const INIT_ADD = 'INIT_ADD';
export const ADD_OBJECT = 'ADD_OBJECT';
export const ADDED_OBJECT = 'ADDED_OBJECT';
export const GET_OBJECTS = 'GET_OBJECTS';
export const SIGN_UP = 'SIGN_UP';
export const LOG_IN = 'LOG_IN';
export const SACUVAJ_PACIJENTE = 'SACUVAJ_PACIJENTE';
export const SACUVAJ_KLINIKE = 'SACUVAJ_KLINIKE';
export const SACUVAJ_KARTON = 'SACUVAJ_KARTON';
export const SACUVAJ_PREGLED = 'SACUVAJ_PREGLED';
export const SACUVAJ_SALE = 'SACUVAJ_SALE';
export const SACUVAJ_DOKTORE = 'SACUVAJ_DOKTORE';
export const SACUVAJ_TIPOVE_PREGLEDA = 'SACUVAJ_TIPOVE_PREGLEDA';
export const SACUVAJ_PREGLEDE = 'SACUVAJ_PREGLEDE';
export const SACUVAJ_PRIJAVLJENOG_KORISNIKA = 'SACUVAJ_PRIJAVLJENOG_KORISNIKA';
export const VRATI_SORTIRANE_PACIJENTE = 'VRATI_SORTIRANE_PACIJENTE';



//export const SACUVAJ_PREGLEDE = 'SACUVAJ_PREGLEDE';