export {
    addObject,
    fetchObjects
} from './object';

export {
    register,
    login,
    pacijenti,
    klinike,
    karton,
    unosPregleda,
    sale,
    doktori,
    tipoviPregleda,
    unosSale,
    izmeniSalu,
    pregledi,
    izmeniTipPregleda,
    unosTipaPregleda,
    izbrisiSalu,
    prijavljenKorisnik,
    sortiraniPacijenti,
    slanjeMaila,
    izmeniPrijavljenogKorisnika,
    obrisiPrijavljenogKorisnika,
    sacuvajObelezenuKliniku,
    slanjeZahteva,
    vratiZahteve,
    brisiZahtev,
    slanjePotvrdnogMaila,
    cuvajIdDoktora,
    sacuvajObelezenogPacijenta,
    bolesti,
    lekovi,
    unosPregledaDoktora,
    sacuvajPregledKarton,
    unosOceneKlinike,
    unosOceneLekara,
    pretraziKlinike,
    traziDoktore,
    zakaziPregled,
    rezervisiSalu,
    zauzeceSale,
    promeniLozinku,
    sacuvajKlinikuProfila,
    slanjeDoktorovogMaila,
    podesiPregled,
    rezervisiSalu2,
    izmeniPregledDoktora,
    adminBriseLekara,
    unosLekara,
    izmeniKliniku,
    obrisiTipPregleda,
    rezervacije,
    sveRezervacije,
    obrisiPrijavljenog,

} from './auth';